Config.vehicleList = {
    ['vehicles'] = {
        {label = locale('compacts'), defaultIndex = 2, dbData = 'car', values = {
            {label = 'Club', vehicleModel = joaat('club'), vehiclePrice = 22000},
            {label = 'Weevil', vehicleModel = joaat('weevil'), vehiclePrice = 20000},
            {label = 'Brioso 300', vehicleModel = joaat('brioso2'), vehiclePrice = 18000 },
            {label = 'Kanjo', vehicleModel = joaat('kanjo'), vehiclePrice = 30000},
            {label = 'Asbo', vehicleModel = joaat('asbo'), vehiclePrice = 25000},
            {label = 'Blista', vehicleModel = joaat('blista'), vehiclePrice = 32000}, 
            {label = 'Issi Classic', vehicleModel = joaat('issi3'), vehiclePrice = 18000},
            {label = 'Rhapsody', vehicleModel = joaat('rhapsody'), vehiclePrice = 32000},
        }},
        {label = locale('coupes'), defaultIndex = 2, dbData = 'car', values = {
            {label = 'Oracle XS', vehicleModel = joaat('oracle'), vehiclePrice = 75000},
            {label = 'Oracle', vehicleModel = joaat('oracle2'), vehiclePrice = 78000},
            {label = 'Zion', vehicleModel = joaat('zion'), vehiclePrice = 82000},
            {label = 'Zion Cabrio', vehicleModel = joaat('zion2'), vehiclePrice = 82000},
            {label = 'Sentinel XS', vehicleModel = joaat('sentinel'), vehiclePrice = 77000},
            {label = 'Sentinel ', vehicleModel = joaat('sentinel2'), vehiclePrice = 80000},
            {label = 'Windsor', vehicleModel = joaat('windsor'), vehiclePrice = 95000},
            {label = 'Windsor Drop', vehicleModel = joaat('windsor2'), vehiclePrice = 95000},
            {label = 'Felon', vehicleModel = joaat('felon'), vehiclePrice = 83000},
            {label = 'Felon GT', vehicleModel = joaat('felon2'), vehiclePrice = 85000},
            {label = 'Postlude', vehicleModel = joaat('postlude'), vehiclePrice = 65000}, 
            {label = 'Previon', vehicleModel = joaat('previon'), vehiclePrice = 68000},
            {label = 'F620', vehicleModel = joaat('f620'), vehiclePrice = 92000},
            {label = 'Exemplar', vehicleModel = joaat('exemplar'), vehiclePrice = 90000},
            {label = 'Cognoscenti Cabrio', vehicleModel = joaat('cogcabrio'), vehiclePrice = 70000},
        }},
        {label = locale('sports'), defaultIndex = 2, dbData = 'car', values = {
            {label = 'NineF Cabrio', vehicleModel = joaat('ninef2'), vehiclePrice = 310000},
            {label = 'Buffalo S', vehicleModel = joaat('buffalo2'), vehiclePrice = 275000}, 
            {label = 'Itali GTO', vehicleModel = joaat('italigto'), vehiclePrice = 350000}, 
            {label = 'Schlagen GT', vehicleModel = joaat('schlagen'), vehiclePrice = 335000},
            {label = 'Panthere', vehicleModel = joaat('panthere'), vehiclePrice = 295000},
            {label = 'Raiden', vehicleModel = joaat('raiden'), vehiclePrice = 390000},
            {label = 'Neon', vehicleModel = joaat('neon'), vehiclePrice = 385000},
            {label = 'Komoda', vehicleModel = joaat('komoda'), vehiclePrice = 305000},
            {label = 'Elegy Retro Custom', vehicleModel = joaat('elegy'), vehiclePrice = 220000},
            {label = 'Comet Retro Custom', vehicleModel = joaat('comet3'), vehiclePrice = 300000},
            {label = 'Flash GT', vehicleModel = joaat('flashgt'), vehiclePrice = 325000},
            {label = 'EightF Drafter', vehicleModel = joaat('drafter'), vehiclePrice = 315000},
            {label = 'Omnis e-GT', vehicleModel = joaat('omnisegt'), vehiclePrice = 395000},
            {label = 'TenF', vehicleModel = joaat('tenf'), vehiclePrice = 385000},
            {label = 'Comet S2', vehicleModel = joaat('comet6'), vehiclePrice = 345000},
            {label = 'Growler', vehicleModel = joaat('growler'), vehiclePrice = 350000},
            {label = 'ZR350', vehicleModel = joaat('zr350'), vehiclePrice = 215000},
            {label = 'Cypher', vehicleModel = joaat('cypher'), vehiclePrice = 317000},
            {label = 'Itali GTO Stinger TT', vehicleModel = joaat('stingertt'), vehiclePrice = 390000},
            {label = 'Remus', vehicleModel = joaat('remus'), vehiclePrice = 215000},
        }},
    },
    ['boats'] = {
        {label = locale('skis'), defaultIndex = 2, dbData = 'boat', values = {
            {label = 'Seashark', vehicleModel = joaat('seashark'), vehiclePrice = 1000}, 
            {label = 'Seashark', vehicleModel = joaat('seashark2'), vehiclePrice = 1000}, 
            {label = 'Seashark', vehicleModel = joaat('seashark3'), vehiclePrice = 1000},
        }},
        {label = locale('boats'), defaultIndex = 2, dbData = 'boat', values = {
            {label = 'Dinghy', vehicleModel = joaat('dinghy'), vehiclePrice = 1000}, 
            {label = 'DinghyB', vehicleModel = joaat('dinghy2'), vehiclePrice = 1000}, 
            {label = 'DinghyC', vehicleModel = joaat('dinghy3'), vehiclePrice = 1000},
            {label = 'DinghyD', vehicleModel = joaat('dinghy4'), vehiclePrice = 1000}, 
        }},
        {label = locale('cruise_boats'), defaultIndex = 2, dbData = 'boat', values = {
            {label = 'Jetmax', vehicleModel = joaat('jetmax'), vehiclePrice = 1000}, 
            {label = 'Speeder', vehicleModel = joaat('speeder'), vehiclePrice = 1000}, 
            {label = 'SpeederB', vehicleModel = joaat('speeder2'), vehiclePrice = 1000},
            {label = 'Squalo', vehicleModel = joaat('squalo'), vehiclePrice = 1000},
            {label = 'Suntrap', vehicleModel = joaat('suntrap'), vehiclePrice = 1000},
            {label = 'Toro', vehicleModel = joaat('toro'), vehiclePrice = 1000},
            {label = 'ToroB', vehicleModel = joaat('toro2'), vehiclePrice = 1000},
            {label = 'Tropic', vehicleModel = joaat('tropic'), vehiclePrice = 1000},
            {label = 'TropicB', vehicleModel = joaat('tropic2'), vehiclePrice = 1000},
            {label = 'Longfin', vehicleModel = joaat('longfin'), vehiclePrice = 1000},
       }},
    },
    ['planes'] = {
        {label = locale('helis'), defaultIndex = 2, dbData = 'plane', values = {
            {label = 'havok', vehicleModel = joaat('havok'), vehiclePrice = 1000}, 
            {label = 'nokota', vehicleModel = joaat('nokota'), vehiclePrice = 1000}, 
        }},
        {label = locale('planes'), defaultIndex = 2, dbData = 'plane', values = {
            {label = 'havok', vehicleModel = joaat('havok'), vehiclePrice = 1000}, 
            {label = 'nokota', vehicleModel = joaat('nokota'), vehiclePrice = 1000}, 
        }},
    },

}