return {
    [0]  = { icon = "fas fa-car" 					},
    [1]  = { icon = "fas fa-car" 					},
    [2]  = { icon = "fas fa-car" 					},
    [3]  = { icon = "fas fa-car" 					},
    [4]  = { icon = "fas fa-car" 					},
    [5]  = { icon = "fas fa-car" 					},
    [6]  = { icon = "fas fa-car" 					},
    [7]  = { icon = "fas fa-car" 					},
    [8]  = { icon = "fas fa-motorcycle"				},
    [9]  = { icon = "fas fa-truck-monster"			},
    [10] = { icon = "fas fa-industry"				},
    [11] = { icon = "fas fa-truck-ramp-box"			},
    [12] = { icon = "fas fa-truck"					},
    [13] = { icon = "fas fa-bicycle"				},
    [14] = { icon = "fas fa-sailboat" 				},
    [15] = { icon = "fas fa-helicopter"				},
    [16] = { icon = "fas fa-plane"					},
    [17] = { icon = "fas fa-taxi"					},
    [18] = { icon = "fas fa-truck-medical"			},
    [19] = { icon = "fas fa-person-military-rifle"	},
    [20] = { icon = "fas fa-truck-ramp-box"			},
    [21] = { icon = "fas fa-train"					},
    [22] = { icon = "fas fa-car"					}
}